#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE
setxkbmap us
i3lock -i $PICTURE
setxkbmap -layout us,ua,ru -option grp:alt_shift_toggle
rm $PICTURE
